export const healthReminders = [
    'Drink a glass of water',
    'Look 20 seconds into the distance (20-20-20 rule)',
    'Stand up and stretch for 30 seconds',
    'Roll your shoulders 5 times',
    'Take 5 deep breaths',
    'Blink rapidly for 10 seconds',
    'Do 10 quick neck tilts',
    'Walk around the room once',
    'Close your eyes and relax for 30 seconds',
    'Shake your hands to release tension',

    'Straighten your posture for 20 seconds',
    'Relax your jaw and unclench your teeth',
    'Stretch your wrists gently',
    'Do 10 slow head turns side to side',
    'Loosen your ankles with small circles',
    'Take a slow, mindful breath in and out',
    'Do a 20-second chest stretch',
    'Lift your arms overhead for 10 seconds',
    'Massage your temples for 15 seconds',
    'Gently squeeze your shoulder blades together',
    'Stand on your toes for 10 seconds',
    'Do 10 calf raises',
    'Stretch your lower back by leaning forward',
    'Relax your eyebrows and forehead',
    'Quickly tidy your workspace for 20 seconds',
    'Check your breathing and slow it down',
    'Look away from your screen and blink slowly',
    'Do 5 slow torso twists',
    'Stretch your fingers wide for 10 seconds',
    'Take a few steps in place',
    'Gently stretch the side of your neck',
    'Do 10 slow arm circles',
    'Do a 20-second quad stretch',
    'Take 3 very deep belly breaths',
    'Do a gentle back arch while seated',
    'Relax your shoulders completely',
    'Do 10 seated leg lifts',
    'Press your palms together and stretch',
    'Smile for 5 seconds to release tension',
    'Take a micro-break and close your eyes briefly',
    'Check in with how your body feels',
    'Stretch your hip flexors for 10 seconds',
    'Roll your ankles 10 times each',
    'Do a gentle hamstring stretch',
    'Sit tall and lift your chest slightly',
    'Massage your forearms briefly',
    'Put your tongue on the roof of your mouth to relax your neck',
    'Yawn intentionally to loosen facial muscles',
    'Do a 10-second shoulder shrug hold',
    'Take 10 slow breaths while counting',
];
